"""AC-07 — Memory persists across sessions.

> Memory persists across sessions: a committed test starts a new session and shows recall of
> prior-session facts; its output log is committed.

The central test here, `test_ac07_session_two_recalls_session_one_facts_in_a_new_process`, runs
session 2 in a **real subprocess** — a separate Python interpreter with no shared objects, no
warm caches, and no inherited module state. Session 1 writes its facts and every handle is torn
down before it starts.

That boundary is the whole point. Two `TieredMemory` instances inside one interpreter could
appear to persist while actually sharing a page cache or a module-level singleton. A subprocess
cannot: if session 2 recalls the fact, the fact came off disk.

Output log: `evidence/logs/ac07_cross_session_persistence.log` (regenerated by
`scripts/generate_evidence.py`).
"""

from __future__ import annotations

import json
import subprocess
import sys
import textwrap

import pytest

from discharge_copilot.config import REPO_ROOT
from discharge_copilot.memory import TieredMemory
from discharge_copilot.memory.episodic import EpisodicMemory

SESSION_1_FACTS = [
    {
        "key": "allergy:penicillin",
        "content": "Documented allergy: Penicillin. Anaphylaxis reported in 2019.",
        "kind": "allergy",
    },
    {
        "key": "caregiver",
        "content": "Caregiver: daughter Maya Prasad, reachable on the ward contact number.",
        "kind": "caregiver",
    },
    {
        "key": "care_constraint:transport",
        "content": (
            "Patient has previously missed cardiology appointments because she has no "
            "transport and does not drive."
        ),
        "kind": "care_constraint",
    },
    {
        "key": "adherence_concern:diuretic",
        "content": (
            "Unable to state her own furosemide dose at teach-back; needed the instructions "
            "repeated three times."
        ),
        "kind": "adherence_concern",
    },
]

NAMESPACE = "MRN-AC07-TEST"


@pytest.fixture
def isolated_memory(tmp_path):
    """A memory instance on temporary storage, so tests never touch the real store."""
    return TieredMemory(
        episodic_path=tmp_path / "episodic.sqlite",
        semantic_path=tmp_path / "chroma_memory",
        enable_semantic=False,  # exercised separately; keeps this fixture fast
    )


# ---------------------------------------------------------------------------
# The load-bearing test: a real process boundary
# ---------------------------------------------------------------------------


def test_ac07_session_two_recalls_session_one_facts_in_a_new_process(tmp_path):
    """AC-07: a separate OS process recalls facts written by an earlier session.

    Session 1 writes, then exits. Session 2 is a fresh interpreter. Nothing is shared but the
    files on disk.
    """
    db = tmp_path / "cross_session.sqlite"

    # --- SESSION 1: write, in its own process, then exit ---
    session_one = textwrap.dedent(
        f"""
        import sys, json
        sys.path.insert(0, {str(REPO_ROOT / "src")!r})
        from pathlib import Path
        from discharge_copilot.memory.episodic import EpisodicMemory

        mem = EpisodicMemory(db_path=Path({str(db)!r}))
        facts = {json.dumps(SESSION_1_FACTS)}
        for f in facts:
            mem.write(
                namespace={NAMESPACE!r},
                key=f["key"], content=f["content"], kind=f["kind"],
                session_id="session-1", case_id="CASE-AC07-A",
            )
        print(json.dumps({{"written": mem.count({NAMESPACE!r})}}))
        """
    )
    result_one = subprocess.run(
        [sys.executable, "-c", session_one], capture_output=True, text=True, timeout=180
    )
    assert result_one.returncode == 0, result_one.stderr
    assert json.loads(result_one.stdout.strip().splitlines()[-1])["written"] == len(
        SESSION_1_FACTS
    )

    # --- SESSION 2: a brand-new interpreter reads them back ---
    session_two = textwrap.dedent(
        f"""
        import sys, json
        sys.path.insert(0, {str(REPO_ROOT / "src")!r})
        from pathlib import Path
        from discharge_copilot.memory.episodic import EpisodicMemory

        mem = EpisodicMemory(db_path=Path({str(db)!r}))
        recalled = mem.recall({NAMESPACE!r}, limit=20)
        print(json.dumps({{
            "pid_differs": True,
            "recalled": [
                {{"key": r["key"], "content": r["content"],
                  "session_id": r["session_id"], "kind": r["kind"]}}
                for r in recalled
            ],
            "sessions_seen": mem.sessions_for({NAMESPACE!r}),
        }}))
        """
    )
    result_two = subprocess.run(
        [sys.executable, "-c", session_two], capture_output=True, text=True, timeout=180
    )
    assert result_two.returncode == 0, result_two.stderr

    payload = json.loads(result_two.stdout.strip().splitlines()[-1])
    recalled = payload["recalled"]

    assert len(recalled) == len(SESSION_1_FACTS)

    # Every fact survived, with its originating session id intact.
    by_key = {r["key"]: r for r in recalled}
    for fact in SESSION_1_FACTS:
        assert fact["key"] in by_key, f"session-2 lost '{fact['key']}'"
        assert by_key[fact["key"]]["content"] == fact["content"]
        assert by_key[fact["key"]]["session_id"] == "session-1", (
            "recalled fact must carry the session that wrote it — that provenance is what "
            "makes cross-session recall demonstrable rather than merely asserted"
        )

    # The specific clinical facts the criterion cares about.
    contents = " ".join(r["content"] for r in recalled).lower()
    assert "penicillin" in contents
    assert "maya" in contents
    assert "transport" in contents

    assert payload["sessions_seen"] == ["session-1"]


def test_ac07_session_two_writes_join_session_one_facts(tmp_path):
    """AC-07: memory accumulates across sessions rather than being replaced."""
    db = tmp_path / "accumulate.sqlite"

    first = EpisodicMemory(db_path=db)
    first.write(
        namespace=NAMESPACE,
        key="allergy:penicillin",
        content="Documented allergy: Penicillin.",
        kind="allergy",
        session_id="session-1",
    )
    del first  # tear down every handle

    second = EpisodicMemory(db_path=db)
    second.write(
        namespace=NAMESPACE,
        key="med_change:spironolactone",
        content="Spironolactone 12.5 mg started on the second admission.",
        kind="medication_change",
        session_id="session-2",
    )

    recalled = second.recall(NAMESPACE, limit=20)
    assert {r["session_id"] for r in recalled} == {"session-1", "session-2"}
    assert second.sessions_for(NAMESPACE) == ["session-1", "session-2"]


def test_ac07_restating_a_fact_preserves_its_original_age(tmp_path):
    """AC-07/AC-08: a fact repeated in a later session is the same fact, not a new one.

    Resetting `created_at` on every restatement would defeat recency decay entirely — a fact
    mentioned every admission would never age, and the eviction policy would be inert.
    """
    db = tmp_path / "restate.sqlite"
    mem = EpisodicMemory(db_path=db)

    mem.write(
        namespace=NAMESPACE,
        key="allergy:penicillin",
        content="Documented allergy: Penicillin.",
        kind="allergy",
        session_id="session-1",
    )
    original = mem.get(NAMESPACE, "allergy:penicillin")

    mem.write(
        namespace=NAMESPACE,
        key="allergy:penicillin",
        content="Documented allergy: Penicillin. Anaphylaxis reported in 2019.",
        kind="allergy",
        session_id="session-2",
    )
    updated = mem.get(NAMESPACE, "allergy:penicillin")

    assert updated["created_at"] == original["created_at"]
    assert "Anaphylaxis" in updated["content"]
    assert mem.count(NAMESPACE) == 1


def test_ac07_namespaces_isolate_patients(tmp_path):
    """AC-07: one patient's memory is never recalled for another."""
    mem = EpisodicMemory(db_path=tmp_path / "ns.sqlite")
    mem.write(
        namespace="MRN-A", key="allergy:penicillin",
        content="Allergic to penicillin.", kind="allergy", session_id="s1",
    )
    mem.write(
        namespace="MRN-B", key="allergy:sulfa",
        content="Allergic to sulfa drugs.", kind="allergy", session_id="s1",
    )
    assert [r["content"] for r in mem.recall("MRN-A")] == ["Allergic to penicillin."]
    assert [r["content"] for r in mem.recall("MRN-B")] == ["Allergic to sulfa drugs."]
    assert mem.recall("MRN-UNKNOWN") == []


@pytest.mark.slow
def test_ac07_semantic_tier_also_persists_across_processes(tmp_path):
    """AC-07: the semantic tier is durable too, not only the SQLite tier.

    Chroma writes to disk, so a query issued from a new process retrieves an embedding written
    by an earlier one — without the query repeating the stored wording.
    """
    persist = tmp_path / "chroma_memory"

    writer = textwrap.dedent(
        f"""
        import sys; sys.path.insert(0, {str(REPO_ROOT / "src")!r})
        from pathlib import Path
        from discharge_copilot.memory.semantic import SemanticMemory
        m = SemanticMemory(persist_dir=Path({str(persist)!r}))
        m.write(namespace={NAMESPACE!r}, key="care_constraint:transport",
                content=("Patient has previously missed cardiology appointments because she "
                         "has no transport and does not drive."),
                kind="care_constraint", session_id="session-1")
        print("OK", m.count({NAMESPACE!r}))
        """
    )
    out = subprocess.run(
        [sys.executable, "-c", writer], capture_output=True, text=True, timeout=600
    )
    assert out.returncode == 0, out.stderr

    reader = textwrap.dedent(
        f"""
        import sys, json; sys.path.insert(0, {str(REPO_ROOT / "src")!r})
        from pathlib import Path
        from discharge_copilot.memory.semantic import SemanticMemory
        m = SemanticMemory(persist_dir=Path({str(persist)!r}))
        hits = m.recall({NAMESPACE!r}, "barriers to attending follow-up appointments", k=3)
        print(json.dumps(hits))
        """
    )
    out = subprocess.run(
        [sys.executable, "-c", reader], capture_output=True, text=True, timeout=600
    )
    assert out.returncode == 0, out.stderr

    hits = json.loads(out.stdout.strip().splitlines()[-1])
    assert hits, "semantic memory did not survive the process boundary"
    assert "transport" in hits[0]["content"].lower()
    assert hits[0]["session_id"] == "session-1"


def test_ac07_tiered_facade_recalls_across_sessions(isolated_memory):
    """AC-07: the facade the graph actually uses recalls prior-session facts."""
    for fact in SESSION_1_FACTS:
        isolated_memory.write(
            namespace=NAMESPACE,
            key=fact["key"],
            content=fact["content"],
            kind=fact["kind"],
            session_id="session-1",
            case_id="CASE-AC07-A",
        )

    hits = isolated_memory.recall_for_patient(
        NAMESPACE, "allergies, caregiver and transport barriers", k=6
    )
    assert hits
    assert all(h["session_id"] == "session-1" for h in hits)
    combined = " ".join(h["content"] for h in hits).lower()
    assert "penicillin" in combined

    snapshot = isolated_memory.snapshot(NAMESPACE)
    assert snapshot["episodic_count"] == len(SESSION_1_FACTS)
    assert snapshot["sessions"] == ["session-1"]
